# https://developers.cloudflare.com/workers/wrangler/configuration/
name = "kyoobit"
main = "src/index.ts"
compatibility_date = "2024-12-29"

# https://developers.cloudflare.com/workers/wrangler/configuration/#types-of-routes
routes = [
    { pattern = "kyoobit.nateroyer.com", custom_domain = true },
    { pattern = "www.kyoobit.net", custom_domain = true },
]

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"
# LOGGING_ENDPOINT = <--- npm run wrangler secret put LOGGING_ENDPOINT

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# https://developers.cloudflare.com/workers/wrangler/configuration/#r2-buckets
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "kyoobit-r2-production"
preview_bucket_name = "public"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
